on: [push, pull_request]
  branches:
  - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.10.0' # Replace with specific Node version : 8.x, 10.x, 12.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: vehicle-history-api
        publish-profile: ${{ secrets.azureWebAppPublishProfile }} # Define secret variable in repository settings as per action documentation
        #package: '.'  #default value is entire repo
        # If your function app project is not located in your repository's root
        # Please consider prefixing the project path in this package parameter
